import { request } from "@/services/apis/client";
import { getStoredBusinessCode } from "@/lib/auth";
import type { Category, CategoryInput, ID, ListQuery, Paginated, Product, ProductInput } from "@/types";

type BackendPage<T> = { content: T[]; page: number; size: number; totalElements: number };
type CategoryDTO = { categoryId: string; name: string; description?: string };
type ProductDTO = { productId: string; categoryId?: string; name: string; sku?: string; barcode?: string; description?: string; unit?: string; purchasePrice?: number; sellingPrice?: number; taxRate?: number; minStock?: number; status?: string };
const base = (resource: string) => `/bizuno/business/${encodeURIComponent(getStoredBusinessCode())}/${resource}`;
const ensureCode = () => { if (!getStoredBusinessCode()) throw new Error("Business session is missing. Please sign in again."); };
const mapCategory = (item: CategoryDTO): Category => ({ id: item.categoryId, name: item.name, description: item.description, productCount: 0, status: "active" });
const mapProduct = (item: ProductDTO): Product => ({ id: item.productId, name: item.name, sku: item.sku ?? "", barcode: item.barcode ?? "", categoryId: item.categoryId ?? "", categoryName: "", unit: item.unit ?? "", purchasePrice: Number(item.purchasePrice ?? 0), sellingPrice: Number(item.sellingPrice ?? 0), taxRate: Number(item.taxRate ?? 0), stock: 0, minStock: Number(item.minStock ?? 0), warehouseId: "", status: item.status?.toLowerCase() === "inactive" ? "inactive" : item.status?.toLowerCase() === "discontinued" ? "discontinued" : "active", description: item.description, createdAt: "" });
const params = (query: ListQuery = {}) => new URLSearchParams({ page: String(Math.max(0, (query.page ?? 1) - 1)), size: String(query.pageSize ?? 10), sortBy: query.sortBy ?? "name", sortDirection: query.sortDir === "desc" ? "desc" : "ASC" });
const productBody = (input: Partial<ProductInput>, includeWarehouse = false) => ({ ...(includeWarehouse && input.warehouseId ? { warehouseId: input.warehouseId } : {}), categoryId: input.categoryId || undefined, name: input.name, barcode: input.barcode || undefined, description: input.description || undefined, unit: input.unit || undefined, purchasePrice: input.purchasePrice, sellingPrice: input.sellingPrice, taxRate: input.taxRate, minStock: input.minStock, status: input.status?.toUpperCase() });

export async function listProducts(query: ListQuery = {}): Promise<Paginated<Product>> { ensureCode(); const [result, categories] = await Promise.all([request<BackendPage<ProductDTO>>(`${base("product")}?${params(query)}`), listCategories()]); const categoryNames = new Map(categories.map((category) => [category.id, category.name])); const rows = result.content.map((item) => ({ ...mapProduct(item), categoryName: categoryNames.get(item.categoryId ?? "") ?? "" })); const search = query.search?.toLowerCase().trim(); return { rows: search ? rows.filter((item) => [item.name, item.sku, item.barcode, item.categoryName].some((value) => value.toLowerCase().includes(search))) : rows, total: result.totalElements, page: result.page + 1, pageSize: result.size }; }
export async function getProduct(id: ID): Promise<Product | undefined> { ensureCode(); return mapProduct(await request<ProductDTO>(`${base("product")}/${id}`)); }
export async function getProductSales(_id: ID) { return []; }
export async function listCategories(): Promise<Category[]> { ensureCode(); const result = await request<BackendPage<CategoryDTO>>(`${base("category")}?${params({ page: 1, pageSize: 100 })}`); return result.content.map(mapCategory); }
export async function createCategory(input: CategoryInput): Promise<Category> { ensureCode(); return mapCategory(await request<CategoryDTO>(base("category"), { method: "POST", body: JSON.stringify({ name: input.name, description: input.description || undefined }) })); }
export async function updateCategory(id: ID, input: Partial<CategoryInput>): Promise<Category> { ensureCode(); return mapCategory(await request<CategoryDTO>(`${base("category")}/${id}`, { method: "PUT", body: JSON.stringify({ name: input.name, description: input.description || undefined }) })); }
export async function deleteCategory(id: ID): Promise<void> { ensureCode(); await request<unknown>(`${base("category")}/${id}`, { method: "DELETE" }); }
export async function createProduct(input: ProductInput): Promise<Product> { ensureCode(); return mapProduct(await request<ProductDTO>(base("product"), { method: "POST", body: JSON.stringify(productBody(input, true)) })); }
export async function updateProduct(id: ID, input: Partial<ProductInput>): Promise<Product> { ensureCode(); return mapProduct(await request<ProductDTO>(`${base("product")}/${id}`, { method: "PUT", body: JSON.stringify(productBody(input)) })); }
export async function deleteProduct(id: ID): Promise<void> { ensureCode(); await request<unknown>(`${base("product")}/${id}`, { method: "DELETE" }); }
