/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as SalesInvoiceIdRouteImport } from './routes/sales.$invoiceId'
import { Route as LoginIndexRouteImport } from './routes/login.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoiceIdRoute = SalesInvoiceIdRouteImport.update({
  id: '/sales/$invoiceId',
  path: '/sales/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/sales/$invoiceId': typeof SalesInvoiceIdRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/sales': typeof SalesIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/sales/$invoiceId': typeof SalesInvoiceIdRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/sales/$invoiceId': typeof SalesInvoiceIdRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/customers/' | '/products/' | '/inventory/' | '/sales/' | '/payments/' | '/reports/' | '/settings/' | '/suppliers/' | '/customers/$customerId' | '/sales/$invoiceId' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customers' | '/products' | '/inventory' | '/sales' | '/payments' | '/reports' | '/settings' | '/suppliers' | '/customers/$customerId' | '/sales/$invoiceId' | '/login'
  id: '__root__' | '/' | '/customers/' | '/products/' | '/inventory/' | '/sales/' | '/payments/' | '/reports/' | '/settings/' | '/suppliers/' | '/customers/$customerId' | '/sales/$invoiceId' | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  SalesInvoiceIdRoute: typeof SalesInvoiceIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$invoiceId': {
      id: '/sales/$invoiceId'
      path: '/sales/$invoiceId'
      fullPath: '/sales/$invoiceId'
      preLoaderRoute: typeof SalesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  SalesInvoiceIdRoute: SalesInvoiceIdRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
